[allowlist]
description = "exclude all infra code"
paths = [
  '''^\.git.*''',
  '''^\.github.*''',
  '''^docs.*''',
  '''^test_package.*''',
  '''^\.gitignore''',
  '''^\.mega-linter\.yml''',
  '''^\.releaserc\.json''',
  '''^CMakeLists\.txt''',
  '''^Doxyfile''',
  '''^LICENSE''',
  '''^NOTICE''',
  '''^README\.md''',
  '''^Versioning\.md''',
  '''^CHANGELOG\.md''',
  '''^build''',
  '''^conan_provider\.cmake''',
  '''^conandata\.yml''',
  '''^conanfile\.py''',
  '''^metadata\.json''',
]
