# .mega-linter.yml
FILTER_REGEX_INCLUDE: "(include|src)/"

ENABLE: "C,CPP,COPYPASTE"
DISABLE: "SPELL"

ENABLE_LINTERS:
  - REPOSITORY_GITLEAKS
  - REPOSITORY_SEMGREP
  - REPOSITORY_CHECKOV
  - REPOSITORY_DEVSKIM

DISABLE_LINTERS:
  - C_CPPLINT
  - CPP_CPPLINT

COPYPASTE_JSCPD_ARGUMENTS:
  - "--pattern"
  - "include/**/*,src/**/*"

REPOSITORY_GITLEAKS_ARGUMENTS:
  - "-c"
  - ".github/misc/.gitleaks.toml"
  - "--verbose"

REPOSITORY_SEMGREP_ARGUMENTS:
  - "--include"
  - "include/"
  - "--include"
  - "src/"

REPOSITORY_CHECKOV_ARGUMENTS:
  - "-d"
  - "."
  - "--skip-path"
  - "include/"
  - "--skip-path"
  - "src/"
  - "--skip-path"
  - "test_package/test/"
  - "--skip-path"
  - "test_package/main.cpp"

REPOSITORY_DEVSKIM_ARGUMENTS:
  - "--include-globs"
  - "**/include/**,**/src/**"
  - "--ignore-globs"
  - "**/test_package/**"

C_CLANG_TIDY:
  ENABLE: true
  CONFIG_FILE: ".github/misc/.clang-tidy"
  FILE_EXTENSIONS: [".h", ".c"]

CPP_CLANG_TIDY:
  ENABLE: true
  CONFIG_FILE: ".github/misc/.clang-tidy"
  FILE_EXTENSIONS: [".hpp", ".cpp"]

C_CLANG_FORMAT:
  ENABLE: true
  CONFIG_FILE: ".github/misc/.clang-format"

CPP_CLANG_FORMAT:
  ENABLE: true
  CONFIG_FILE: ".github/misc/.clang-format"

SARIF_REPORTER: true
MARKDOWN_SUMMARY_REPORTER: true
