# .github/workflows/lint.yml

name: Code Linting

on:
  workflow_dispatch: # 仅允许手动触发

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # 或者其他你想要的 LTS 版本

      - name: Install MegaLinter
        run: npm install -g @oxsecurity/megalinter

      - name: Run MegaLinter
        working-directory: .
        run: |
          megalinter-runner \
            --config .github/misc/.mega-linter.yml \
            --output-folder reports

      - name: Upload Lint Report
        uses: actions/upload-artifact@v4
        with:
          name: lint-reports
          path: reports/
